version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/nacl
  - /modules/nat-gateway
  - /modules/route-table
  - /modules/security-group
  - /modules/subnet-group
  - /modules/vpc
  schedule:
    interval: weekly
