# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to dx-gateway module."
  name: ":floppy_disk: dx-gateway"
- color: "fbca04"
  description: "This issue or pull request is related to ipam module."
  name: ":floppy_disk: ipam"
- color: "fbca04"
  description: "This issue or pull request is related to ipam-resource-discovery module."
  name: ":floppy_disk: ipam-resource-discovery"
- color: "fbca04"
  description: "This issue or pull request is related to nacl module."
  name: ":floppy_disk: nacl"
- color: "fbca04"
  description: "This issue or pull request is related to nat-gateway module."
  name: ":floppy_disk: nat-gateway"
- color: "fbca04"
  description: "This issue or pull request is related to prefix-list module."
  name: ":floppy_disk: prefix-list"
- color: "fbca04"
  description: "This issue or pull request is related to reachability-analyzer-path module."
  name: ":floppy_disk: reachability-analyzer-path"
- color: "fbca04"
  description: "This issue or pull request is related to route-table module."
  name: ":floppy_disk: route-table"
- color: "fbca04"
  description: "This issue or pull request is related to security-group module."
  name: ":floppy_disk: security-group"
- color: "fbca04"
  description: "This issue or pull request is related to subnet-group module."
  name: ":floppy_disk: subnet-group"
- color: "fbca04"
  description: "This issue or pull request is related to vpc module."
  name: ":floppy_disk: vpc"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-endpoint-service module."
  name: ":floppy_disk: vpc-endpoint-service"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-gateway-endpoint module."
  name: ":floppy_disk: vpc-gateway-endpoint"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-interface-endpoint module."
  name: ":floppy_disk: vpc-interface-endpoint"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-peering module."
  name: ":floppy_disk: vpc-peering"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-peering-accepter module."
  name: ":floppy_disk: vpc-peering-accepter"
- color: "fbca04"
  description: "This issue or pull request is related to vpc-peering-requester module."
  name: ":floppy_disk: vpc-peering-requester"
